#!/usr/bin/env python3

try:
    import torch.cuda

    print(f"Torch: is CUDA available: {torch.cuda.is_available()}")
    print(f"Torch: CUDA device: {torch.cuda.device}")
    # print(torch.cuda.get_device_capability())
except:
    print("Torch: CUDA not available")

try:
    import tensorflow as tf

    print(tf.__version__)
    print(tf.config.list_physical_devices())
    print("pip install tensorflow-gpu")
except:
    print("Tensorflow: not available")
