# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.6/c2cciutils/schema.json

publish:
  pypi:
    packages: []
  docker:
    dispatch: false
    repository:
      github:
        server: ghcr.io
        versions:
          - version_tag
          - version_branch
          - rebuild
          - feature_branch
      dockerhub:
        versions: []
    images:
      - name: sbrunner/clean-documents
