#!/usr/bin/env python3


try:
    import cv2

    print(f"OpenCV: version: {cv2.__version__}")
except Exception as e:
    print("OpenCV: not available")
    print(e)


try:
    import tensorflow as tf

    print(f"Tensorflow: version: {tf.__version__}")
    for device in tf.config.list_physical_devices():
        print(f"Tensorflow: {device.device_type}: {device.name}")
except Exception as e:
    print("Tensorflow: not available")
    print(e)

try:
    import torch.cuda

    print(f"Torch: is CUDA available: {torch.cuda.is_available()}")
    print(f"Torch: CUDA device: {torch.cuda.device}")
    # print(torch.cuda.get_device_capability())
except Exception as e:
    print("Torch: CUDA not available")
    print(e)
