#!/usr/bin/env python3

import glob
import os.path
import shutil

import pikepdf


def _main():
    for path in glob.glob("/home/sbrunner/Documents Stéphane/originals/**/*.pdf", recursive=True):
        max_image_size = 0
        with pikepdf.open(path) as pdf:
            for page in pdf.pages:
                for image in page.images.values():
                    pdfimage = pikepdf.PdfImage(image)
                    max_image_size = max(max_image_size, pdfimage.width * pdfimage.height)

        if max_image_size < 100000:
            # Move file to clean-dat if he didn't already exists
            dest = os.path.join("clean-data", os.path.basename(path))
            if not os.path.exists(dest):
                shutil.move(path, dest)
            else:
                print(f"{dest} already exists")


if __name__ == "__main__":
    _main()
