#!/usr/bin/env python3


import glob
import subprocess


def _main() -> None:
    for path in glob.glob("clean-data/*.pdf"):
        print(path)
        # convert pdf to png in 300 dpi
        subprocess.run(["convert", "-density", "300", path, f"{path[:-4]}.png"], check=True)


if __name__ == "__main__":
    _main()
